import { ChecklistValueType } from './database';

export interface ChecklistItemDefinition {
  key: string;
  label: string;
  valueType: ChecklistValueType;
  isMandatory: boolean;
  requiresPhoto: boolean;
  requiresVideo: boolean;
  minPhotos: number;
  maxPhotos?: number;
  selectOptions?: { value: number; label: string }[];
  description?: string;
}

export interface ChecklistCategory {
  key: string;
  label: string;
  icon: string;
  order: number;
  items: ChecklistItemDefinition[];
}

export const CHECKLIST_TEMPLATE: ChecklistCategory[] = [
  {
    key: 'exterior',
    label: 'Exterior',
    icon: 'car',
    order: 1,
    items: [
      {
        key: 'exterior_body_condition',
        label: 'Estado de la Chapa',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 3,
        selectOptions: [
          { value: 1, label: 'Mal estado' },
          { value: 2, label: 'Correcto' },
          { value: 3, label: 'Muy buen estado' },
        ],
      },
      {
        key: 'exterior_paint_thickness',
        label: 'Espesímetro',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 4,
        selectOptions: [
          { value: 1, label: 'Reparaciones importantes' },
          { value: 2, label: 'Reparación localizada' },
          { value: 3, label: 'Valores de fábrica' },
        ],
      },
      {
        key: 'exterior_headlights_condition',
        label: 'Estado de Faros',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 2,
        selectOptions: [
          { value: 1, label: 'Perfecto' },
          { value: 2, label: 'Difuminados' },
          { value: 3, label: 'Con humedad' },
          { value: 4, label: 'Agrietados' },
        ],
      },
      {
        key: 'exterior_headlights_date',
        label: 'Fecha de Faros',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 2,
        selectOptions: [
          { value: 1, label: 'No coinciden' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correctos' },
        ],
      },
      {
        key: 'exterior_tire_wear',
        label: 'Desgaste de Neumáticos',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 4,
        selectOptions: [
          { value: 1, label: 'Irregular' },
          { value: 2, label: 'Leve/Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'exterior_tire_dot_front',
        label: 'DOT Neumáticos Delanteros',
        valueType: 'text',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        description: 'Fecha de fabricación (ej: 2319 = semana 23 de 2019)',
      },
      {
        key: 'exterior_tire_dot_rear',
        label: 'DOT Neumáticos Traseros',
        valueType: 'text',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        description: 'Fecha de fabricación (ej: 2319 = semana 23 de 2019)',
      },
      {
        key: 'exterior_wheel_condition',
        label: 'Estado de Llantas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 4,
        selectOptions: [
          { value: 1, label: 'Daño evidente' },
          { value: 2, label: 'Marcas leves' },
          { value: 3, label: 'Correctas' },
        ],
      },
      {
        key: 'exterior_tire_depth_front_right',
        label: 'Nivel Neumático Delantero Derecho (mm)',
        valueType: 'number',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'exterior_tire_depth_front_left',
        label: 'Nivel Neumático Delantero Izquierdo (mm)',
        valueType: 'number',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'exterior_tire_depth_rear_right',
        label: 'Nivel Neumático Trasero Derecho (mm)',
        valueType: 'number',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'exterior_tire_depth_rear_left',
        label: 'Nivel Neumático Trasero Izquierdo (mm)',
        valueType: 'number',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'exterior_brakes_condition',
        label: 'Frenos (Pastillas/Discos)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 2,
        selectOptions: [
          { value: 1, label: 'Desgaste alto' },
          { value: 2, label: 'Desgaste medio' },
          { value: 3, label: 'Buen estado' },
        ],
      },
      {
        key: 'exterior_windshield_condition',
        label: 'Luna Delantera',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Daño grave' },
          { value: 2, label: 'Daño moderado' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'exterior_glass_originality',
        label: 'Originalidad de Lunas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 2,
        selectOptions: [
          { value: 1, label: 'No originales' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Originales' },
        ],
      },
      {
        key: 'exterior_panel_alignment',
        label: 'Alineación de Paneles',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 3,
        selectOptions: [
          { value: 1, label: 'Desalineados' },
          { value: 2, label: 'Leve desalineación' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'exterior_screws_originality',
        label: 'Tornillería (Capó/Puertas/Aletas)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 3,
        selectOptions: [
          { value: 1, label: 'Manipulados' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Originales' },
        ],
      },
      {
        key: 'exterior_fuel_cap',
        label: 'Tapa Combustible/Carga',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: true,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'No funciona' },
          { value: 2, label: 'Fallo leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'exterior_tow_hitch',
        label: 'Bola de Remolque',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 0, label: 'No tiene' },
          { value: 1, label: 'Incorrecta' },
          { value: 2, label: 'Homologada no original' },
          { value: 3, label: 'Original' },
        ],
      },
      {
        key: 'exterior_wheel_lock',
        label: 'Antirrobo de Llantas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'No tiene' },
          { value: 2, label: 'Sin llave' },
          { value: 3, label: 'Con llave' },
        ],
      },
      {
        key: 'exterior_keys',
        label: 'Número de Llaves',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: '1 Llave' },
          { value: 2, label: '2 Llaves' },
        ],
      },
    ],
  },
  {
    key: 'interior',
    label: 'Interior',
    icon: 'layout-dashboard',
    order: 2,
    items: [
      {
        key: 'interior_wear_consistency',
        label: 'Desgaste (Volante/Pomo/Pedales)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 3,
        selectOptions: [
          { value: 1, label: 'Excesivo vs kilometraje' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Coherente' },
        ],
      },
      {
        key: 'interior_instrument_cluster',
        label: 'Cuadro de Instrumentos',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Testigos encendidos' },
          { value: 2, label: 'Correcto' },
        ],
      },
      {
        key: 'interior_mirrors_windows',
        label: 'Retrovisores/Ventanas Eléctricas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'No funciona' },
          { value: 2, label: 'Fallo leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'interior_seatbelt_dates',
        label: 'Cinturones (Fecha)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 2,
        selectOptions: [
          { value: 1, label: 'No coherentes' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correctos' },
        ],
      },
      {
        key: 'interior_seatbelt_mechanism',
        label: 'Cinturones (Mecanismo)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'interior_multimedia',
        label: 'Pantallas/Multimedia',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'interior_climate_control',
        label: 'Climatizador',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 2, label: 'Correcto' },
        ],
      },
      {
        key: 'interior_manuals',
        label: 'Manuales del Vehículo',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'No están' },
          { value: 2, label: 'Parcial' },
          { value: 3, label: 'Completos' },
        ],
      },
      {
        key: 'interior_lights',
        label: 'Luces Interiores/Exteriores',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'interior_extras',
        label: 'Extras (Techo, HUD, Keyless)',
        valueType: 'select',
        isMandatory: false,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'interior_trunk_tray',
        label: 'Bandeja de Maletero',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Falta' },
          { value: 2, label: 'Dañada' },
          { value: 3, label: 'Correcta' },
        ],
      },
      {
        key: 'interior_emergency_kit',
        label: 'Kit de Emergencia',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Falta' },
          { value: 2, label: 'Parcial' },
          { value: 3, label: 'Completo' },
        ],
      },
      {
        key: 'interior_electrical_systems',
        label: 'Sistema Eléctrico (Sensores/Asistentes)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'interior_speakers',
        label: 'Altavoces',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
    ],
  },
  {
    key: 'engine',
    label: 'Motor y Mecánica',
    icon: 'settings',
    order: 3,
    items: [
      {
        key: 'engine_visual_leaks',
        label: 'Fugas Visuales',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 3,
        selectOptions: [
          { value: 1, label: 'No correcto' },
          { value: 2, label: 'Humedad leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_oil_color',
        label: 'Color del Aceite',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Quemado' },
          { value: 2, label: 'Aceptable' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_oil_thickness',
        label: 'Espesor del Aceite',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Pastoso' },
          { value: 2, label: 'Denso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_metal_shavings',
        label: 'Virutas en Tapón',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Presencia' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_cold_start',
        label: 'Arranque en Frío',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: true,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Mal arranque' },
          { value: 2, label: 'Aceptable' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_idle_stability',
        label: 'Ralentí (Estabilidad)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Inestable' },
          { value: 2, label: 'Aceptable' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_idle_noise',
        label: 'Ralentí (Ruidos)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Metálicos' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_rev_test',
        label: 'Acelerones (Motor Caliente)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: true,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Humo/Ruido anómalo' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_coolant',
        label: 'Refrigerante',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Nivel/Color mal' },
          { value: 2, label: 'Aceptable' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_parts_originality',
        label: 'Originalidad de Piezas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 2,
        selectOptions: [
          { value: 1, label: 'No originales' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Originales' },
        ],
      },
      {
        key: 'engine_power_steering',
        label: 'Dirección Asistida',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_suspension',
        label: 'Suspensión/Silentblocks',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 2,
        selectOptions: [
          { value: 1, label: 'Rotos' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_rust',
        label: 'Óxidos',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 2,
        selectOptions: [
          { value: 1, label: 'Relevante' },
          { value: 2, label: 'Superficial' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_humidity',
        label: 'Humedades (Moquetas)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Relevante' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_exhaust',
        label: 'Escape',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Fuga' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_exhaust_gas',
        label: 'Gases de Escape',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: true,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Humo anómalo' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Sin humo' },
        ],
      },
      {
        key: 'engine_wipers',
        label: 'Limpiaparabrisas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Fallo' },
          { value: 2, label: 'Leve' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_clutch',
        label: 'Embrague',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Dureza/Fricción' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_oil_level_hot',
        label: 'Nivel de Aceite (Motor Caliente)',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Mal' },
          { value: 2, label: 'A vigilar' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'engine_belts',
        label: 'Correas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Incidencia' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
    ],
  },
  {
    key: 'obd',
    label: 'Diagnosis OBD',
    icon: 'cpu',
    order: 4,
    items: [
      {
        key: 'obd_initial_diagnosis',
        label: 'Diagnosis Inicial',
        valueType: 'text',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        description: 'Registro de errores antes de borrado',
      },
      {
        key: 'obd_post_test_diagnosis',
        label: 'Diagnosis Post-Prueba',
        valueType: 'text',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        description: 'Registro de errores después de borrado y prueba',
      },
      {
        key: 'obd_km_kombi',
        label: 'KM Cuadro (Kombi)',
        valueType: 'number',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'obd_km_ecu',
        label: 'KM ECU Motor',
        valueType: 'number',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'obd_km_tcu',
        label: 'KM TCU Caja',
        valueType: 'number',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'obd_km_abs',
        label: 'KM ABS',
        valueType: 'number',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'obd_km_fraud_check',
        label: 'Verificación Fraude Kilometraje',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Inconsistencia detectada' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Coherente' },
        ],
      },
      {
        key: 'obd_units_check',
        label: 'Lectura Unidades (EPS, SRS, Gateway)',
        valueType: 'text',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        description: 'Resumen de unidades de control leídas',
      },
      {
        key: 'obd_analysis',
        label: 'Análisis y Contraste',
        valueType: 'text',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        description: 'Contrastar fallos OBD con realidad física del vehículo',
      },
    ],
  },
  {
    key: 'test_drive',
    label: 'Prueba de Conducción',
    icon: 'gauge',
    order: 5,
    items: [
      {
        key: 'test_drive_steering',
        label: 'Dirección',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Desalineada' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcta' },
        ],
      },
      {
        key: 'test_drive_braking',
        label: 'Frenada',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Vibración' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcta' },
        ],
      },
      {
        key: 'test_drive_gear_changes',
        label: 'Cambio de Marchas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Tirones' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
      {
        key: 'test_drive_gear_entry',
        label: 'Entrada de Marchas',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Dura/Rasca' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcta' },
        ],
      },
      {
        key: 'test_drive_power',
        label: 'Potencia',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Falta potencia' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Lineal' },
        ],
      },
      {
        key: 'test_drive_suspension',
        label: 'Suspensión Dinámica',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Rebotes/Ruidos' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcta' },
        ],
      },
      {
        key: 'test_drive_noise_insulation',
        label: 'Aislamiento Acústico',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: false,
        minPhotos: 0,
        selectOptions: [
          { value: 1, label: 'Ruido viento/ventanas' },
          { value: 2, label: 'Dudoso' },
          { value: 3, label: 'Correcto' },
        ],
      },
    ],
  },
  {
    key: 'documentation',
    label: 'Documentación y Extras',
    icon: 'file-text',
    order: 6,
    items: [
      {
        key: 'docs_whatsapp_commercial',
        label: 'WhatsApp del Comercial',
        valueType: 'text',
        isMandatory: false,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        description: 'Captura de pantalla de la conversación (opcional)',
      },
      {
        key: 'docs_video_360',
        label: 'Vídeo 360º',
        valueType: 'boolean',
        isMandatory: true,
        requiresPhoto: false,
        requiresVideo: true,
        minPhotos: 0,
        description: 'Vertical, 10s exterior + 5s interior, sin voz',
      },
      {
        key: 'docs_cover_photo',
        label: 'Foto Portada',
        valueType: 'boolean',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        description: '16:9 vertical, coche de cara, llantas giradas',
      },
      {
        key: 'docs_teil1',
        label: 'Papeles Teil 1',
        valueType: 'boolean',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'docs_teil2',
        label: 'Papeles Teil 2',
        valueType: 'boolean',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'docs_maintenance_history',
        label: 'Historial de Mantenimiento',
        valueType: 'select',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        selectOptions: [
          { value: 1, label: 'Incompleto' },
          { value: 2, label: 'Parcial' },
          { value: 3, label: 'Completo' },
        ],
      },
      {
        key: 'docs_vin_verification',
        label: 'Verificación VIN',
        valueType: 'boolean',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
        description: 'Coincidencia VIN físico vs papeles',
      },
      {
        key: 'docs_manufacturer_plate',
        label: 'Placa del Fabricante',
        valueType: 'boolean',
        isMandatory: true,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
      {
        key: 'docs_coc',
        label: 'COC (Certificado de Conformidad)',
        valueType: 'boolean',
        isMandatory: false,
        requiresPhoto: true,
        requiresVideo: false,
        minPhotos: 1,
      },
    ],
  },
];

export function getChecklistItemDefinition(
  itemKey: string
): ChecklistItemDefinition | undefined {
  for (const category of CHECKLIST_TEMPLATE) {
    const item = category.items.find((i) => i.key === itemKey);
    if (item) return item;
  }
  return undefined;
}

export function getCategoryByKey(
  categoryKey: string
): ChecklistCategory | undefined {
  return CHECKLIST_TEMPLATE.find((c) => c.key === categoryKey);
}
